### PR TITLE
Use Java 11

### LINKED ISSUE #78: Upgrade to OpenJDK 11
### Name and Version

bitnami/jenkins:2

### What is the problem this feature will solve?

As OpenJDK 8 has reached EOL, upgrading to JDK 11 would help in provided bug fixes and security update.

### What is the feature you are proposing to solve the problem?

Upgrade the JDK in the image to use JDK 11. I could make the PR if this good looks to be done.

### What alternatives have you considered?

Split a image tag for jdk11. Due to the request from VMWare, using any image other than provided from Bitnami would be forbidden.

### PR DESCRIPTION
**Pull request by jhult**
Use Java 11 instead of Java 1.8.

More reading:

- https://www.jenkins.io/blog/2021/08/17/docker-images-use-jdk-11-by-default/
- https://www.jenkins.io/doc/administration/requirements/upgrade-java-guidelines/
- https://www.jenkins.io/doc/administration/requirements/jenkins-on-java-11/

- fixes #78

### CODE REVIEW

**Comment by jhult** [comment]
@miguelaeh, any news on this?

**Comment by miguelaeh** [comment]
Hi @jhult ,
We are sorry, we don't have the time to work on this yet, we are a small team with limited capacity. We cannot provide an ETA but we will update this thread once we have news. 
Thank you for your patience.

**Comment by jhult** [comment]
Bump

**Comment by viceice** [comment]
This is a blocker for me. I like to switch to this image too.

**Comment by miguelaeh** [comment]
Unfortunately, we had not the time to work on this. The task is still on our backlog. I will try to increase the priority but still, I cannot provide an ETA for this.

**Comment by foal** [comment]
See the warning `Java 11 is the recommended version to run Jenkins on; please consider upgrading.` in the latest (2.319.3) version of your image. 

Please, find a time to update the Java.

**Comment by miguelaeh** [comment]
Hi guys,
We raised the priority. We will update the thread once we have news

**Comment by tonyhhyip** [comment]
Would it be possible to use another image tag for JDK 11, says `2-jdk11`? Then, people would be able to keep the JDK 8 and have the options of switching to JDK 11

**Comment by tonyhhyip** [comment]
This has become sort of blocker for me, as I have no options in switching images to official Jenkins image due the request of VMWare which I must use image provided from Bitnami.

**Comment by javsalgar** [comment]
Just a note to let you know that I'm working on it

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision of the container using Java 11. 2.319.3-debian-10-r13. Closing this PR.

**Pull request closed without merging**
